# Generated by Django 5.0.4 on 2024-04-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mbl_number', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=10)),
            ],
        ),
    ]
